[phases.setup]
nixPkgs = ["...", "chromium"]
aptPkgs = ["...", "libx11-xcb1", "libxcomposite1", "libxdamage1", "libxi6", "libxtst6", "libnss3", "libxrandr2", "libasound2", "libpangocairo-1.0-0", "libatk1.0-0", "libatk-bridge2.0-0", "libgtk-3-0"]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "node index.js"